modid = "hexcasting"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "1.20" # TODO: switch back to main

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    "{_common.src}/generated/resources",
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexcasting/_export/generated"

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/common/lib/hex/HexActions.java"
regex = "{^_pattern_regex}"

[textures]
missing = [
    "hexcasting:conjured_block",
    "hexcasting:conjured_light",
]

[template]
icon = "../art/logo.png"
include = [
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hex Casting"
author = "petrak@, Alwinfy"
show_landing_text = true

# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/at/petrak/hexcasting"

[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/at/petrak/hexcasting/fabric"

[_forge]
src = "../Forge/src"
package = "{src}/main/java/at/petrak/hexcasting/forge"
